version: "3.7"
services:
  gateway:
    image: node:16-alpine
    command: |
      sh -c "npm install && npm run start:dev"
    working_dir: /srv/app
    volumes:
      - .:/srv/app
      - /srv/app/dist

    ports:
      - 3000:3000
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    